// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: customer/grpc/proto/gender.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Female Type = 0
	Type_Male   Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Female",
		1: "Male",
	}
	Type_value = map[string]int32{
		"Female": 0,
		"Male":   1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_customer_grpc_proto_gender_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_customer_grpc_proto_gender_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_customer_grpc_proto_gender_proto_rawDescGZIP(), []int{0}
}

type Gender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.Type" json:"type,omitempty"`
}

func (x *Gender) Reset() {
	*x = Gender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_grpc_proto_gender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gender) ProtoMessage() {}

func (x *Gender) ProtoReflect() protoreflect.Message {
	mi := &file_customer_grpc_proto_gender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gender.ProtoReflect.Descriptor instead.
func (*Gender) Descriptor() ([]byte, []int) {
	return file_customer_grpc_proto_gender_proto_rawDescGZIP(), []int{0}
}

func (x *Gender) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Female
}

var File_customer_grpc_proto_gender_proto protoreflect.FileDescriptor

var file_customer_grpc_proto_gender_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x06, 0x47, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x2a, 0x1c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x6c, 0x65,
	0x10, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_customer_grpc_proto_gender_proto_rawDescOnce sync.Once
	file_customer_grpc_proto_gender_proto_rawDescData = file_customer_grpc_proto_gender_proto_rawDesc
)

func file_customer_grpc_proto_gender_proto_rawDescGZIP() []byte {
	file_customer_grpc_proto_gender_proto_rawDescOnce.Do(func() {
		file_customer_grpc_proto_gender_proto_rawDescData = protoimpl.X.CompressGZIP(file_customer_grpc_proto_gender_proto_rawDescData)
	})
	return file_customer_grpc_proto_gender_proto_rawDescData
}

var file_customer_grpc_proto_gender_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_customer_grpc_proto_gender_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_customer_grpc_proto_gender_proto_goTypes = []interface{}{
	(Type)(0),      // 0: proto.Type
	(*Gender)(nil), // 1: proto.Gender
}
var file_customer_grpc_proto_gender_proto_depIdxs = []int32{
	0, // 0: proto.Gender.type:type_name -> proto.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_customer_grpc_proto_gender_proto_init() }
func file_customer_grpc_proto_gender_proto_init() {
	if File_customer_grpc_proto_gender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_customer_grpc_proto_gender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_customer_grpc_proto_gender_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customer_grpc_proto_gender_proto_goTypes,
		DependencyIndexes: file_customer_grpc_proto_gender_proto_depIdxs,
		EnumInfos:         file_customer_grpc_proto_gender_proto_enumTypes,
		MessageInfos:      file_customer_grpc_proto_gender_proto_msgTypes,
	}.Build()
	File_customer_grpc_proto_gender_proto = out.File
	file_customer_grpc_proto_gender_proto_rawDesc = nil
	file_customer_grpc_proto_gender_proto_goTypes = nil
	file_customer_grpc_proto_gender_proto_depIdxs = nil
}
